
ELEMENT = 'Element'
LIST = 'List'

# JTYPES
VOID_JTYPE = 'V'
INTEGER_JTYPE = 'I'
STRING_JTYPE = 'Ljava/lang/String;'

INTEGER_LIST_CLASS = 'listlang/objects/List'
INTEGER_LIST_JTYPE = 'L%s;' % INTEGER_LIST_CLASS

type_map = {ELEMENT: INTEGER_JTYPE, LIST: INTEGER_LIST_JTYPE}

RESERVED_LOCALS = 10

TEMPORARY_STORE_VAR_1 = 0
TEMPORARY_STORE_VAR_2 = 1

TARGET_CLASS_NAME = 'listlang/program/LLMain'